# exmaple 
# https://www.api-football.com/documentation-v3#tag/Leagues/operation/get-leagues

### Fixtures

GET {{host}}/fixtures?season=2022&league=39
Content-Type: application/json
x-rapidapi-host: v3.football.api-sports.io
x-rapidapi-key: {{api-key}}


### Leagues

GET {{host}}/leagues?type=league
Content-Type: application/json
x-rapidapi-host: v3.football.api-sports.io
x-rapidapi-key: {{api-key}}